#!/usr/bin/env bash

#===================================================
#
#    Copyright (c) 2023
#      SMASH Hybrid Team
#
#    GNU General Public License (GPLv3 or later)
#
#===================================================

#----------------------------------------------------------------------------#
#     __  __      __         _     __   __  __                ____           #
#    / / / /_  __/ /_  _____(_)___/ /  / / / /___ _____  ____/ / /__  _____  #
#   / /_/ / / / / __ \/ ___/ / __  /  / /_/ / __ `/ __ \/ __  / / _ \/ ___/  #
#  / __  / /_/ / /_/ / /  / / /_/ /  / __  / /_/ / / / / /_/ / /  __/ /      #
# /_/ /_/\__, /_.___/_/  /_/\__,_/  /_/ /_/\__,_/_/ /_/\__,_/_/\___/_/       #
#       /____/                                                               #
#                                                                            #
#----------------------------------------------------------------------------#

source bash/logger.bash


Print_Trace            "Trace message"
Print_Debug            "Debug message"
Print_Info             "Information message"
Print_Attention        "Attention message"
Print_Warning          "Warning message"
Print_Error            "Error"
( Print_Fatal_And_Exit   "Fatal error, exit!" )
Print_Internal_And_Exit  "Internal, for developer error"
