IC:
    Executable: /path/to/smash
    Software_keys:
        Modi:
            Collider:
                Projectile:
                    Particles: {2212: 82, 2112: 126} #Lead208
                Target:
                    Particles: {2212: 82, 2112: 126} #Lead208
                Sqrtsnn: 17.3

Hydro:
    Executable: /path/to/vHLLE
    Software_keys:
        etaS: 0.15
        Rg: 1.4
        Rgz: 0.7

Sampler:
    Executable: /path/to/hadron-sampler

Afterburner:
    Executable: /path/to/smash
    Add_spectators_from_IC: TRUE
