IC:
    Executable: /path/to/smash
    Software_keys:
        Modi:
            Collider:
                Projectile:
                    Particles: {2212: 79, 2112: 118} #Gold197
                Target:
                    Particles: {2212: 79, 2112: 118} #Gold197
                Sqrtsnn: 7.7

Hydro:
    Executable: /path/to/vHLLE
    Software_keys:
        nx: 51
        ny: 51
        nz: 51

Sampler:
    Executable: /path/to/hadron-sampler
    Software_keys:
        number_of_events: 50

Afterburner:
  Executable: /path/to/smash
  Software_keys:
    General:
        Nevents: 50
