Version: 1.8
Logging:
    default: INFO

General:
    Modus:         List
    Time_Step_Mode: None
    Delta_Time:    0.1
    End_Time:      10000.0    # make sure runtime is long enough for back-propagation
    Randomseed:    -1
    Nevents:       2000

Output:
    Particles:
        Format:          ["Binary"]

Modi:
    List:
        # If the build directory is not located in the smash directory anymore,
        # the absolute path specified below will not work anymore.
        # You can alternatively pass the path directly from the command line
        # with the "-c" command:
        # ./smash -i <path to config file> -c 'Modi: { List: { File_Directory: <path to file that is read in> } }
        File_Directory: "../build/"
        File_Prefix: "sampling"
        Shift_Id: 0
