Version: 1.7

Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: Fixed
    Delta_Time:     1.0
    End_Time:       600.0
    Randomseed:     -1
    Nevents:        1

Output:
    Output_Interval: 5.0
    Initial_Conditions:
      Format: ["ASCII"]


Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197

        Sqrtsnn: 8.8
        Fermi_Motion: frozen
