import numpy as np
import matplotlib.pyplot as plt
import re
import argparse
import os

'''
    This script reads in the freezeout hypersurface created by CORNELIUS within
    vHLLE and reformats it such that:
    - No trailing whitespaces at the beginning of the line
    - Different line entries are separated by only whitespace
    - Hypersurface patches with vanishing energy density or temperature are
      removed. Those patches usually originate from the boundaries of the EoS,
      where the baryon density may become unphysically large for certain regions
      of the energy density. Since those patches are seemingly unphysical, they
      can be ignored.

    The reformatted file can be applied within Sangwook's Cooper-Frye sampler
    for particlization.
'''

# pass arguments from the command line to the script
parser = argparse.ArgumentParser()
parser.add_argument("--vhlle_hypersurface", required = True,
                    help="Freezeout hypersurface generated by means of vhlle.")
parser.add_argument("--output_file", required = False,
                    help="Freezeout hypersurface with non-zero contributions only.")
args = parser.parse_args()

if args.output_file:
    hypersurface_contributions = open(args.output_file, 'w')
else:
    contributions_file = os.path.dirname(args.vhlle_hypersurface) + '/freezeout_contributions.dat'
    hypersurface_contributions = open(contributions_file, 'w')

with open(args.vhlle_hypersurface, 'r') as f:
    for line in f:
        line = re.sub(' +', ' ',line) # remove whitespaces between entries
        newline = line[1:]
        line = line.split()

        if ((float(line[13]) > 0.0) and (float(line[12]) > 0.0)):
            # if non-zero energy-density and temperature, print to hypersurface
            # file that contains only non-zero contributions
            hypersurface_contributions.write(newline)

hypersurface_contributions.close()
