Version: 1.8

Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: Fixed
    Delta_Time:     1.0
    End_Time:       2000.0
    Randomseed:     -1
    Nevents:        1

Output:
    Initial_Conditions:
      Format: ["ASCII", "Binary", "Oscar2013"]
      Extended: True

Modi:
    Collider:
        Projectile:
            Particles: {2212: 44, 2112: 52}  # Ru
            Custom:
                # Path needs to be updated accordingly
                File_Directory: "/lustre/hyihp/nsass/smash-vhlle-hybrid/custom_nucleus"
                File_Name: "ru96case1-smash_triaxial-ico3-10017.dat"
        Target:
            Particles: {2212: 44, 2112: 52}
            Custom:
                # Path needs to be updated accordingly
                File_Directory: "/lustre/hyihp/nsass/smash-vhlle-hybrid/custom_nucleus"
                File_Name: "ru96case1-smash_triaxial-ico3-10017.dat"

        Fermi_Motion: frozen
        Impact:
            Value: 5.8
