IC:
    Executable: /path/to/smash
    Software_keys:
        Modi:
            Collider:
                Projectile:
                    Particles: {2212: 82, 2112: 126} #Lead208
                Target:
                    Particles: {2212: 82, 2112: 126} #Lead208
                Sqrtsnn: 17.3
                Initial_Conditions:
                    Type: "Constant_Tau"
                    Proper_Time_Scaling: 1

Hydro:
    Executable: /path/to/vHLLE
    Config_file: /path/to/handler/configs/predef_configs/EPJA_58-11-230/vhlle_hydro
    Software_keys:
        etaS: 0.15
        Rg: 1.4
        Rgz: 0.7

Sampler:
    Executable: /path/to/hadron-sampler
    Software_keys:
        bulk: 0
        ecrit: 0.5

Afterburner:
    Executable: /path/to/smash
    Software_keys:
        Collision_Term:
            Cross_Section_Scaling: 1
